version: "2"
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: jing
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  jing-api:
    container_name: jing-api
    image: jingc12/jing-api
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    command:
      - --spring.datasource.url=jdbc:postgresql://db:5432/customer



networks:
  db:
    driver: bridge

volumes:
  db:


